### ISSUE TITLE
replace 'lte' with 'le' on Query in issue_service

### ISSUE THREAD

**Issue by EthanCloin** [EthanCloin/issue-tracker-backend#11]
# Summary
'lte' is not a valid kwarg for Query. less than or equal keyword is 'le'

Replace this in the issue_service file so that the parameter is respected

**Comment by yash-0501** [comment]
Hi @EthanCloin , I am a new contributor, can I please take up this issue?

**Comment by EthanCloin** [comment]
go for it! appreciate your contribution.

**Comment by EthanCloin** [comment]
fixed in IntegrationTesting_EC branch
